# DB
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/medicuore
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.flyway.loggers=DEBUG
# Application name
spring.application.name=medicuore
spring.jmx.default-domain=medicuore
server.servlet.contextPath=/medicuore
# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
log4j2.configurationFile=log4j2.properties
# Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto=update
# Spring Security user
spring.security.user.name=admin
spring.security.user.password=Studio55
spring.security.user.roles=ADMIN
# Swagger
springdoc.api-docs.path=/medicuore-api-docs
springdoc.swagger-ui.path=/medicuore-swagger-ui.html
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.use-root-path=true
